import { Hono } from "hono";
import type { AppEnv } from "../types";
import { requireAdmin, requireFinance } from "../auth";
import { currentMonth, generateTxnId } from "../db";
import { auditEntity, ensureOperationalSchema, requireOpenMonth } from "../ops";
import { boundedText, money, validMonth } from "../validation";
export const donationsRoute=new Hono<AppEnv>();

donationsRoute.get("/",requireAdmin,async c=>{await ensureOperationalSchema(c.env);return c.json((await c.env.DB.prepare("SELECT * FROM donations ORDER BY created_at DESC").all()).results)});
donationsRoute.post("/",requireFinance,async c=>{await ensureOperationalSchema(c.env);const admin=c.get("admin")!;const b=await c.req.json<any>();const donor=boundedText(b.donor_name,120,true);const amount=money(b.amount);const note=boundedText(b.note,1000);const month=b.month||currentMonth(c.env.FUND_TIMEZONE||"Indian/Maldives");if(!donor||amount===null)return c.json({error:'Valid donor name and positive amount are required'},400);if(!validMonth(month))return c.json({error:'Month must use YYYY-MM'},400);try{await requireOpenMonth(c.env,month)}catch(e:any){return c.json({error:e.message},409)}let memberId:null|number=null;if(b.member_id!=null){const m=await c.env.DB.prepare('SELECT id FROM members WHERE id=?').bind(Number(b.member_id)).first<any>();if(!m)return c.json({error:'Member not found'},404);memberId=Number(m.id)}const txn=await generateTxnId(c.env,"D");const r=await c.env.DB.prepare("INSERT INTO donations(txn_id,donor_name,member_id,amount,note,logged_by,transaction_month,status) VALUES(?,?,?,?,?,?,?,'active')").bind(txn,donor,memberId,amount,note||null,admin.id,month).run();await auditEntity(c.env,admin.id,"donation_created","donation",Number(r.meta.last_row_id),null,{txn_id:txn,donor_name:donor,member_id:memberId,amount,note,month});return c.json({id:r.meta.last_row_id,txn_id:txn},201)});
donationsRoute.delete("/:id",requireFinance,async c=>{const admin=c.get("admin")!;const id=Number(c.req.param("id"));const b=await c.req.json().catch(()=>({})) as any;const before=await c.env.DB.prepare("SELECT * FROM donations WHERE id=?").bind(id).first<any>();if(!before)return c.json({error:"Not found"},404);const month=before.transaction_month||before.created_at.slice(0,7);try{await requireOpenMonth(c.env,month)}catch(e:any){return c.json({error:e.message},409)}const reason=boundedText(b.reason,500)||'Voided by admin';await c.env.DB.prepare("UPDATE donations SET status='voided',voided_by=?,voided_at=datetime('now'),void_reason=? WHERE id=?").bind(admin.id,reason,id).run();const after=await c.env.DB.prepare('SELECT * FROM donations WHERE id=?').bind(id).first<any>();await auditEntity(c.env,admin.id,"donation_voided","donation",id,before,after);return c.json({ok:true})});
