import { Hono } from "hono";
import type { AppEnv } from "../types";
import { requireAdmin, requireFinance } from "../auth";
import { generateTxnId } from "../db";
import { auditEntity, ensureOperationalSchema, requireOpenMonth } from "../ops";
export const donationsRoute=new Hono<AppEnv>();

donationsRoute.get("/",requireAdmin,async c=>{await ensureOperationalSchema(c.env);return c.json((await c.env.DB.prepare("SELECT * FROM donations ORDER BY created_at DESC").all()).results)});
donationsRoute.post("/",requireFinance,async c=>{await ensureOperationalSchema(c.env);const admin=c.get("admin")!;const b=await c.req.json<{donor_name:string;amount:number;note?:string;month?:string}>();const month=b.month||new Date().toISOString().slice(0,7);try{await requireOpenMonth(c.env,month)}catch(e:any){return c.json({error:e.message},409)}const txn=await generateTxnId(c.env,"D");const r=await c.env.DB.prepare("INSERT INTO donations(txn_id,donor_name,amount,note,logged_by,transaction_month,status) VALUES(?,?,?,?,?,?,'active')").bind(txn,b.donor_name.trim(),Number(b.amount),b.note||null,admin.id,month).run();await auditEntity(c.env,admin.id,"donation_created","donation",Number(r.meta.last_row_id),null,{txn_id:txn,...b,month});return c.json({id:r.meta.last_row_id,txn_id:txn},201)});
donationsRoute.delete("/:id",requireFinance,async c=>{const admin=c.get("admin")!;const id=Number(c.req.param("id"));const b=await c.req.json().catch(()=>({})) as any;const before=await c.env.DB.prepare("SELECT * FROM donations WHERE id=?").bind(id).first<any>();if(!before)return c.json({error:"Not found"},404);const month=before.transaction_month||before.created_at.slice(0,7);try{await requireOpenMonth(c.env,month)}catch(e:any){return c.json({error:e.message},409)}await c.env.DB.prepare("UPDATE donations SET status='voided',voided_by=?,voided_at=datetime('now'),void_reason=? WHERE id=?").bind(admin.id,b.reason||"Voided by admin",id).run();await auditEntity(c.env,admin.id,"donation_voided","donation",id,before,{...before,status:'voided'});return c.json({ok:true})});
