import { request } from "./client";

export const electionsApi = {
  list: () => request("/api/elections"),
  get: (id) => request(`/api/elections/${id}`),
  readiness: (id) => request(`/api/elections/${id}/readiness`),
  repairApplicationSync: (id) => request(`/api/elections/${id}/repair-application-sync`, { method:"POST" }),
  summary: (id) => request(`/api/elections/${id}/summary`),
  notifications: (id) => request(`/api/elections/${id}/notifications`),
  dashboard: () => request("/api/elections/dashboard"),
  archive: () => request("/api/elections/archive"),
  create: (data) => request("/api/elections", { method:"POST", body:JSON.stringify(data) }),
  update: (id,data) => request(`/api/elections/${id}`, { method:"PATCH", body:JSON.stringify(data) }),
  extendApplications: (id,applications_close_at) => request(`/api/elections/${id}/extend-applications`, { method:"POST", body:JSON.stringify({applications_close_at}) }),
  addPosition: (id,data) => request(`/api/elections/${id}/positions`, { method:"POST", body:JSON.stringify(data) }),
  addCandidate: (id,data) => request(`/api/elections/${id}/candidates`, { method:"POST", body:JSON.stringify(data) }),
  apply: (id,data) => request(`/api/elections/${id}/applications`, { method:"POST", body:JSON.stringify(data) }),
  withdrawApplication: (id,applicationId) => request(`/api/elections/${id}/applications/${applicationId}/withdraw`, { method:"POST" }),
  reviewApplication: (id,applicationId,decision,reason="") => request(`/api/elections/${id}/applications/${applicationId}/review`, { method:"POST", body:JSON.stringify({decision,reason}) }),
  reopenApplication: (id,applicationId) => request(`/api/elections/${id}/applications/${applicationId}/reopen`, { method:"POST" }),
  reassignApplication: (id,applicationId,position_id) => request(`/api/elections/${id}/applications/${applicationId}/reassign`, { method:"POST", body:JSON.stringify({position_id}) }),
  withdrawCandidate: (id,candidateId,reason) => request(`/api/elections/${id}/candidates/${candidateId}/withdraw`, { method:"POST", body:JSON.stringify({reason}) }),
  remindNonVoters: (id) => request(`/api/elections/${id}/remind-nonvoters`, { method:"POST" }),
  certify: (id) => request(`/api/elections/${id}/certify`, { method:"POST" }),
  startRunoff: (id,data) => request(`/api/elections/${id}/runoffs`, { method:"POST", body:JSON.stringify(data) }),
  closeRunoff: (id,runoffId) => request(`/api/elections/${id}/runoffs/${runoffId}/close`, { method:"POST" }),
  voteRunoff: (id,runoffId,candidate_ids) => request(`/api/elections/${id}/runoffs/${runoffId}/vote`, { method:"POST", body:JSON.stringify({candidate_ids}) }),
  currentExco: () => request("/api/elections/exco/current"),
  excoTerms: () => request("/api/elections/exco/terms"),
  currentHandover: () => request("/api/elections/exco/handover/current"),
  updateHandoverItem: (handoverId,itemId,data) => request(`/api/elections/exco/handover/${handoverId}/items/${itemId}`, { method:"PATCH", body:JSON.stringify(data) }),
  completeHandover: (handoverId,notes="") => request(`/api/elections/exco/handover/${handoverId}/complete`, { method:"POST", body:JSON.stringify({notes}) }),
  timeline: (id) => request(`/api/elections/${id}/timeline`),
  excoWorkboard: () => request("/api/elections/exco/workboard"),
  createResponsibility: (data) => request("/api/elections/exco/responsibilities", { method:"POST", body:JSON.stringify(data) }),
  updateResponsibility: (id,data) => request(`/api/elections/exco/responsibilities/${id}`, { method:"PATCH", body:JSON.stringify(data) }),
  responsibilityHistory: (id) => request(`/api/elections/exco/responsibilities/${id}/history`),
  close: (id) => request(`/api/elections/${id}/close`, { method:"POST" }),
  deleteUnusedDraft: (id) => request(`/api/elections/${id}`, { method:"DELETE" }),
  vote: (id,selections) => request(`/api/elections/${id}/vote`, { method:"POST", body:JSON.stringify({selections}) }),
};
